### ISSUE TITLE
Java port inspired by Traverson

### ISSUE THREAD

**Issue by MikeRocke** [traverson/traverson#100]
Hello there,

Hope you are well. I work for AutoTrader.co.uk [[https://github.com/autotraderuk](https://github.com/autotraderuk)] and we wrote a Java library inspired by this! 

We are hoping to open source this soon, and wondered if we could use the name ‘Traverson4j’. 

I was not sure which was the best way to contact the relevant people, so if you could direct me, it would be highly appreciated!

Thanks

Mike

**Comment by basti1302** [comment]
Traverson4j sounds fine, you have my blessing to use the name. Would you be interested in having the repository in the Traverson GitHub org? This is totally optional, if you want to have it in AutoTrader's org for marketing reasons or whatnot, I'm fine with that, too. I'd like to at least link to your project when it has been published.

By the way, are you aware of https://docs.spring.io/spring-hateoas/docs/0.23.0.RELEASE/api/org/springframework/hateoas/client/Traverson.html ? It is another (earlier) Java port of Traverson, albeit with less features then Traverson currently has, I think.

**Comment by MikeRocke** [comment]
Awesome! :)

I can't see any problem the projects being linked, I will speak to the powers in charge regarding where the repository can be hosted.

It is interesting you mention the spring hateoas version. We originally noticed the port when building a new web service using the server side code. We had some client side adoption issues which led us to build a version lighter on dependencies and interchangeable of http clients.

**Comment by basti1302** [comment]
Closing this for now. Feel free to ping me again if anything new happens here.
