### ISSUE TITLE
jquery-ui.min.js:6 Uncaught TypeError: Cannot read property 'step' of undefined     at String.<anonymous> (jquery-ui.min.js:6)     at each (jquery-3.2.1.slim.min.js:2)     at Function.l.hook (jquery-ui.min.js:6)     at jquery-ui.min.js:6     at jquery-ui.min.js:6     at jquery-ui.min.js:6     at jquery-ui.min.js:6

### ISSUE THREAD

**Issue by im-noob** [traverson/traverson#102]
i got this error 
******************************************************************************************************

localhost/:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459WRhyzbi.woff2
localhost/:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459W1hyzbi.woff2
localhost/:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459WZhyzbi.woff2
localhost/:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459Wdhyzbi.woff2
localhost/:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2
localhost/:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHjxAwXjeu.woff2
localhost/:1 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHjx4wXg.woff2
all.js:5 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459WRhyzbi.woff2
all.js:5 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459W1hyzbi.woff2
all.js:5 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459WZhyzbi.woff2
all.js:5 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459Wdhyzbi.woff2
all.js:5 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/montserrat/v12/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2
all.js:5 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHjxAwXjeu.woff2
all.js:5 Slow network is detected. Fallback font will be used while loading: https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHjx4wXg.woff2
jquery-3.2.1.slim.min.js:2 jQuery.Deferred exception: $(...).autocomplete is not a function TypeError: $(...).autocomplete is not a function
    at HTMLDocument.<anonymous> (http://localhost/new/laravel/OT/OT/OnlineTest/public/:454:23)
    at j (https://code.jquery.com/jquery-3.2.1.slim.min.js:2:30203)
    at k (https://code.jquery.com/jquery-3.2.1.slim.min.js:2:30517) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.slim.min.js:2
k @ jquery-3.2.1.slim.min.js:2
jquery-3.2.1.slim.min.js:2 Uncaught TypeError: $(...).autocomplete is not a function
    at HTMLDocument.<anonymous> ((index):454)
    at j (jquery-3.2.1.slim.min.js:2)
    at k (jquery-3.2.1.slim.min.js:2)
(anonymous) @ (index):454
j @ jquery-3.2.1.slim.min.js:2
k @ jquery-3.2.1.slim.min.js:2

When im tring to use auto complete

*************************************************************************************************************
<form class="form-inline my-2 my-lg-0">
		      <input id = "search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
		      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

<script type="text/javascript">
			$( function() {
			    var availableTags = [
			      "ActionScript",
			      "AppleScript",
			      "Asp",
			      "BASIC",
			      "C",
			      "C++",
			      "Clojure",
			      "COBOL",
			      "ColdFusion",
			      "Erlang",
			      "Fortran",
			      "Groovy",
			      "Haskell",
			      "Java",
			      "JavaScript",
			      "Lisp",
			      "Perl",
			      "PHP",
			      "Python",
			      "Ruby",
			      "Scala",
			      "Scheme"
			    ];
			    $( "#search" ).autocomplete({
			      source: availableTags
			    });
			  } );
		</script>

******************************************************************************************************
Here is what i included 
_______________________________________________________________________________________________________

		<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  		<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  		
  		

  		
  		<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" />
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

**Comment by basti1302** [comment]
I have no clue what this even has to do with traverson in the first place?
