### ISSUE TITLE
POSTing raw string value gets stringified

### ISSUE THREAD

**Issue by richardson-trevor** [traverson/traverson#103]
Is there a way to `POST` to an endpoint at the end of a traversal and not have it stringified? What I'm looking to do is POST payload of TSV data. Unfortunately, when I send `"data"` to the server, it ends up getting sent as `""data""` (notice the double quotes). It looks like I could potentially override jsonReplacer that was added in https://github.com/traverson/traverson/pull/69/files, but wanted to see if I was missing something a more appropriate way. Appreciate any guidance.

**Comment by richardson-trevor** [comment]
Worth noting here that we are using a custom MIME type for this POST's Content-Type header. Thinking that may play into this more strongly than I initially imagined.

**Comment by basti1302** [comment]
A fix has landed in 6.1.0. Thanks for the report.
