### ISSUE TITLE
Get embeded resource from direct URL with slashes

### ISSUE THREAD

**Issue by savinov** [traverson/traverson#105]
If I put first argument to the follow() method with direct URL and call getResource(), then I get the error:

> Could not find a matching link nor an embedded document for ...

Why?

`newRequest().follow('some/resource/with/embedded')
            .getResource((error, document) => {
            }
`

CURL returns result with embedded without any errors.

Do I have to follow all the links from the root and retrieve all the data at each step to get target embedded resource?

**Comment by basti1302** [comment]
Sorry for the late reply. Could you provide the complete snippt of your traverson usage, in particular  also the `traverson.from` call? Also, please provide the CURL curl that you use to compare it to.

**Comment by basti1302** [comment]
Closing for now due to lack of info. @savinov feel free to reopen once you find the time to provide what I asked for.
