### ISSUE TITLE
Update typescript section of the user guide

### ISSUE THREAD

**Issue by bowl-of-petunias** [traverson/traverson#112]
The typescript section of the [user-guide](https://github.com/traverson/traverson/blob/master/user-guide.markdown#typescript-types) contains a dead links to [traverson-tsd-ambient](https://github.com/retyped/traverson-tsd-ambient). Is the [@typed/traversion](https://www.npmjs.com/package/@types/traverson) npm package the correct replacement?

**Comment by basti1302** [comment]
Fixed, thanks for reporting.
