### ISSUE TITLE
Use Traverson with React Native

### ISSUE THREAD

**Issue by simon-scherzinger** [traverson/traverson#113]
Hi Bastian,

I hope you are well.

Today I tried to use our module [ec.sdk](https://github.com/entrecode/ec.sdk) with React Native and stumbled upon a few issues. `ec.sdk` relies heavily upon traverson and traverson-hal.

The main problem is that React Native does not include any node standard library modules and when building the project it will fail since it is not able to resolve those.

The issues only rise in the bundled json adapter and is caused by `jsonpath-plus`. I tried replacing it with `jsonpath` but the issues are worse there. Since I'm only using traverson-hal adapter I tried and removed `lib/json_adapter.js` completely. With this setup traverson will work with React Native.

I would like to suggest to you a 'little'  refactor of traverson. Would it be ok with you to remove JSONPath support from traverson core module and replace the bundled `lib/json_adapter.js` with one without JSONPath support? The current JSONPath adapter could be outsourced like traverson-hal is already. This would enable users who rely on JSONPath support to migrate with reasonable effort.

I would be happy to help with a PR. Plase let me know what you think about my suggestions.

Take care,

Simon

**Comment by simon-scherzinger** [comment]
see PR #114

**Comment by basti1302** [comment]
closing in favor of #114
