### ISSUE TITLE
Use fetch API instead of request

### ISSUE THREAD

**Issue by raubel** [traverson/traverson#124]
My application uses heavily the native [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and I would like to use traverson as well.
So I would like to make traverson use fetch instead of request under the hood?

I guess this is possible using the _withRequestLibrary_ method. Has such a fetch/traverson adapter already been implemented?

**Comment by basti1302** [comment]
Sorry, this slipped through the cracks. I do not know of any adapter for using fetch with withRequestLibrary. In the long run, things might happen that make this better for you, see https://github.com/traverson/traverson/issues/134.
