### ISSUE TITLE
Traverson breaking in Angular 6+

### ISSUE THREAD

**Issue by nseney1** [traverson/traverson#127]
**Describe the bug**
We use traverson in one of our angular applications. I recently upgraded our angular version from 5.0 to 7.0 and one of the dependencies(jsonpath-plus) being pulled in from traverson can no longer be built.  
```Module not found: Error: Can't resolve 'vm' in 'path/to/node_modules/traverson/node_modules/jsonpath-plus/lib'```

I wanted to make sure this wasn't an issue specific to our project so I reproduced it with a brand new angular 7 application.

**To Reproduce**
1. Create a new project using the Angular CLI.
2. use npm to install traverson
3. Make an api call using traverson

**Expected behavior**
The angular application to be built without errors.

**Node.js (please complete the following information):**
 - OS: Ubuntu 16.04
 - Node.js version: 8.12.0
 - Traverson Version: 6.1.1

**Comment by simon-scherzinger** [comment]
Hey nseney1,

I had similar issue with React Native. The module bundler wanted to resolve node core modules and failed doing so.

Try and add the following to your package.json:

```json
"browser": {
  "vm": false
}
```

This should tell Angular not to search for the `vm` module during build time.

Hope this helps.

Simon

**Comment by nseney1** [comment]
Hi Simon,

Adding that to the package.json did work. Can you explain a bit more as to why adding this to the package.json works? Is the module not exported properly and that's why it can no longer be resolved at build time? Or is the module export
