### ISSUE TITLE
traverson returns wrong URL for 2nd page of resource

### ISSUE THREAD

**Issue by gefupi** [traverson/traverson#133]
**Description**
Using traverson (6.1.1) with traverson-hal (6.1.0) to fetch URL (or list of entities) from 2nd page of a paged HAL resource does not work as expected.

**Prerequisites**
I have a spring boot REST service running, that provides a paged resource represented using JSON+HAL.
The service responds to a GET request to "http://localhost:8080/myresource" with 
(_for readability I removed the 'myresource' elements_):
```
{
  "_embedded" : {
    "myresources" : [ {$myresource_elemnt}, ... ]
  },
  "_links" : {
    "first" : {
      "href" : "http://localhost:8080/myresources?page=0&size=20"
    },
    "self" : {
      "href" : "http://localhost:8080/myresources{?page,size,sort}",
      "templated" : true
    },
    "next" : {
      "href" : "http://localhost:8080/myresources?page=1&size=20"
    },
    "last" : {
      "href" : "http://localhost:8080/myresources?page=1&size=20"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile/myresources"
    },
    "search" : {
      "href" : "http://localhost:8080/myresources/search"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 35,
    "totalPages" : 2,
    "number" : 0
  }
}
```

**To Reproduce**
1. I run the attached javascript file [traverson-template-debug.js.txt](https://github.com/traverson/traverson/files/3141725/traverson-template-debug.js.txt) with `nodejs traverson-template-debug.js`.
It uses traverson (& traverson-hal) to fetch and print a resource URL.

**Current behavior**
```
$ nodejs traverson-template-debug.js 
[DEBUG] request page: 1 with size: 20
[DEBUG]: URL error is - null
[DEBUG]: URL data is following:
http://localhost:8080/myresources
```

**Expected behavior**
The correct URL http://localhost:8080/myresources?page=1&size=20 is fetched.

**Additional Notes**
In the request logging of my spring boot service I get the following:
```
2019-05-03 12:34:09.484 DEBUG 6841 --- [nio-8080-exec-8] o.s.w.f.CommonsRequestLoggingFilter      : Before request [uri=/]
2019-05-03 12:34:09.489 DEBUG 6841 --- [nio-8080-exec-8] o.s.w.f.CommonsRequestLoggingFilter      : REQUEST DATA : uri=/]
2019-05-03 12:34:09.508 DEBUG 6841 --- [nio-8080-exec-9] o.s.w.f.CommonsRequestLoggingFilter      : Before request [uri=/myresources?page=1&size=20]
2019-05-03 12:34:09.537 DEBUG 6841 --- [nio-8080-exec-9] o.s.w.f.CommonsRequestLoggingFilter      : REQUEST DATA : uri=/myresources?page=1&size=20]
```

This looks like the templating and traversal is working, 
but I still end up with the wrong URL in data from traverson.

**Behavior for 1st page (works as expected)**
If the script is changed to request the 1st page the output is as expected:
```
$ nodejs traverson-template-debug.js 
[DEBUG] request page: 0 with size: 20
[DEBUG]: URL error is - null
[DEBUG]: URL data is following:
http://localhost:8080/myresources?page=0&size=20
```

**Comment by basti1302** [comment]
Hi,

thanks for the great, detailed report. I have built a test-case to reproduce the behaviour you described, but I cannot reproduce it. I see the following output:

```
[DEBUG]: URL error is - null
[DEBUG]: URL data is following:
http://localhost:8080/myresources?page=1&size=20 
```

Could you please run your test again like that:

```
TRAVERSON_LOGGING=true nodejs traverson-template-debug.js
````

And then post the resulting output here? My current guess is that your server gives a different response than the one you posted after following the `myresource` link – maybe that link does not lead to `http://localhost:8080/myresource`, but to some slightly different URL which in turn has a different HTTP response?

**Comment by gefupi** [comment]
Thanks for the advise to use traverson logging.

As it turns out the [**server has a bug**](https://jira.spring.io/browse/DATAREST-1117).


Only if page equals 0 and size equals 20 the generated self link is:
```
http://localhost:8080/myresources{?page,size,sort}
```
For all other values page and size are not provided as part of the templated self link:
```
http://localhost:8080/matchings{&sort}
```
