### ISSUE TITLE
Is following embedded documents available?

### ISSUE THREAD

**Issue by igordeoliveirasa** [traverson/traverson#139]
I'd like to understand, if HAL specifications teach us to embed array of docs with its self links, why Traverson is not able to walk through them?

Thanks.

**Comment by travi** [comment]
could you clarify your use case? it's not clear what exactly you are hoping for.

are you already using the hal adapter? checking the embedded resource should be the default behavior: https://github.com/traverson/traverson-hal#embedded-documents

**Comment by igordeoliveirasa** [comment]
Ok, thanks for your answer!

Lets supoose I followed /orders,... I received a json containing 5 orders inside _embedded key. Id like to keep navigating through each embedded order.

**Comment by travi** [comment]
assuming that you intend to traverse through a specific order, you need to define a selector as part of your path definition: https://github.com/traverson/traverson-hal#selecting-from-a-collection-of-embedded-resources

**Comment by igordeoliveirasa** [comment]
Oh Travi!! Thank you so much! I wasnt expecting those info could be on this link! Thank you so much! Now I got it!

👏🏻👏🏻👏🏻👏🏻🤙🏻

**Comment by travi** [comment]
great. i'll close this for now, but feel free to re-open if you hit any additional road blocks with it

**Comment by igordeoliveirasa** [comment]
@travi I'd like to understand something about HATEOAS/HAL Architecture.. Lets go..

I saw some tutorials when user followed ["me", "posts"] and it revealed a doc containing 10 embedded docs (paginated) and some links like self, next, prev, last, first and find{?id}... Ok, my question is: I really need to list those embedded posts before use find{?id} resource?

**Comment by igordeoliveirasa** [comment]
Is it possible to create multiple _links using same name? Example:

`
_links = {
{rel: "posts", href:"/posts"}, // for get and post usage
{rel: "posts", href:"/posts/{id}", templated: true}, // for find usage
}
`

**Comment by basti1302** [comment]
> Ok, my question is: I really need to list those embedded posts before use find{?id} resource?

That entirely depends on what the server/the API you connect to offers. If the server offers a `find{?id}` directly as a link from the root resource, you can follow it directly. There's nothing in the HAL spec that dictates how the resources are structured or linked between.

```
_links = {
{rel: "posts", href:"/posts"}, // for get and post usage
{rel: "posts", href:"/posts/{id}", templated: true}, // for find usage
}
```

I don't think that would be valid HAL, but this would:
```
{
    "_links": {
      "posts": [{
          "href": "/posts"
      },{
          "href": "/posts/{id}",
          "templated": true
      }]
    }
}
```

See https://tools.ietf.org/html/draft-kelly-json-hal-08#section-4.1.1:

> It is an object whose property names are link relation types (as
>    defined by [RFC5988]) and values are either a Link Object **or an array
>    of Link Objects**.

Or here: http://stateless.co/hal_specification.html - section "Representing Multiple Links With The Same Relation"

**Comment by basti1302** [comment]
Also, for general questions about HAL (instead of questions about traverson / traverson-hal), you might want to check out these resources:
- https://groups.google.com/forum/#!forum/hypermedia-web
- https://github.com/mikekelly/hal_specification/issues

**Comment by igordeoliveirasa** [comment]
@basti1302 Oh my friend THANK YOU SO MUCH! Your answers were very valuable to me!!!

**Comment by igordeoliveirasa** [comment]
Is wrapping Traverson a good practice? Its due to the fact that I would like to call refresh token route if current Bearer token is expired. I guess the only way to do that is wrapping Traverson, Am I right?
