### ISSUE TITLE
v7.0.0 missing browser dependencies

### ISSUE THREAD

**Issue by jelovac** [traverson/traverson#157]
**Describe the bug**

After updating from v6 to v7 I am getting the following error:

```
Failed to compile.

./node_modules/traverson/traverson.js
Module not found: Can't resolve 'minilog' in '/home/***/frontend/node_modules/traverson'
```

**To Reproduce**

1. Remove existing traverson packages: `npm remove traverson-hal traverson` --save
2. Install the latest version: `npm install traverson traverson-hal --save`
3. This results in the following:  'Project fails to compile due to missing dependencies.'

**Expected behavior**

Traverson dependencies install properly.

**Node.js (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node version: 12.16.1
 - NPM version: 6.14.5
 - Traverson Version: 7.0.0

**Additional context**

Investigating traverson package.json I see that minilog is defined under "browser" property, however I do not have the browser directory inside downloaded package when I install v7.

Reverting to v6.1.1 I can see that the directory exists.

**Comment by basti1302** [comment]
https://github.com/traverson/traverson/blob/master/CHANGELOG.md#breaking-changes

Support for EOL Node.js versions has been dropped with traverson@7.0.0.

**Comment by basti1302** [comment]
Sorry, misread your original report, disregard my previous post.

**Comment by basti1302** [comment]
@travi I guess that would be due to https://github.com/traverson/traverson/commit/b59a7b320d6cc443a2a346c52769c567f8a7a844

Seems like we need to `browser` there, too, as it contains the shims referenced in https://github.com/traverson/traverson/blob/master/package.json#L122-L133

WDYT?

**Comment by travi** [comment]
yeah, likely to be the issue. i don't use traverson in the browser, so i didnt have a good way to verify in that context.

i've been been working [package-preview](https://www.npmjs.com/package/package-preview) in some of my other projects in order to be able to run tests against the bundled version of a package. might be worth us working that in somewhere to see if we could catch this type of issue.

i'll get a fix pushed out for the inclusion of the `browser/` directory

**Comment by jelovac** [comment]
Hi,

I can confirm that it works now.

Thank you for the quick fix!

Best regards,
Vladimir

**Comment by travi** [comment]
Thanks for the follow up! Glad it took care of the problem.
