### ISSUE TITLE
Traverson with Hydra and JSON-LD

### ISSUE THREAD

**Issue by sglocastic** [traverson/traverson#96]
I am still new to the hypermedia and semantic web principles and concepts but I would like to use traverson with some Hydra/JSON-LD APIs. Can traverson be used for this and are there any plans for appropriate plugins?

**Comment by basti1302** [comment]
Currently there are no plug-ins for these media types. I also have no plans to implement them. Would you like to take a shot at that? I certainly would support you as much as possible if you would like to try. 

The plug-in for JSON-HAL could serve as a starting point/template for this: https://github.com/traverson/traverson-hal

**Comment by basti1302** [comment]
Closing for now.
