### ISSUE TITLE
how do i build a api?

### ISSUE THREAD

**Issue by jimmywarting** [traverson/traverson#98]
This libs looks cool for consuming a API. but are there any cool npm packages for actually making a  HATEOAS api?

**Comment by basti1302** [comment]
I usually just use express or but there might be more specialized things out there. I honestly don't know. I'll leave this ticket open for a while, maybe someone else wants to chime in, although the GitHub issues of some random HATEOAS related project (like Traverson) might not be the optimal place for asking ;-)

**Comment by jimmywarting** [comment]
Felt like asking this here, since this is more NodeJS related
