### ISSUE TITLE
GET request sending content-length header

### ISSUE THREAD

**Issue by enrique-ramirez** [traverson/traverson#99]
This is a bit of a weird scenario, and I'm not entirely sure if this is a bug or a problem in my code (or maybe in the API I'm using). I'll try my best to describe it in as much detail as possible:

I'm using traverson and traverson-hal. Here's my setup:

```js
// api.js
import traverson from 'traverson'
import JsonHalAdapter from 'traverson-hal'

traverson.registerMediaType(JsonHalAdapter.mediaType, JsonHalAdapter)

const api = traverson
              .from('https://lvh.me/api')
              .jsonHal()
              .withRequestOptions({
                headers: {
                  Accept: 'application/json',
                  'Content-Type': 'application/json',
                },
                withCredentials: true,
              })

export default api
```

```js
// Somefile
import api from './api'

api.follow('some:resource').post(data, (err, response) => {
    if (err) {throw err}
    console.log(response)
})
```

That's pretty much all I'm using. Now, here's what's happening:

1) I'm forcing `application/json` as the `Accept` and `Content-Type` headers because the API I'm using does not understand `application/hal+json`, even though that's what it returns (missconfiguration on the API end).

2) I need `withCredentials: true` because the API uses cookies for authentication. Without this, the API responds with a 302 and a redirect to sign in.

3) Once I reach the `follow` line, this is what I can see in the Network console:
    1. OPTIONS request to `https://lvh.me/api`, returns 200
    2. GET request to `https://lvh.me/api`, returns 200
    3. OPTIONS request to `https://lvh.me/api/some:resource` (not actual URL, but you get the idea), returns 200
    4. GET request to `https://lvh.me/api/some:resource`, returns 302
    5. POST request to `https://lvh.me/api/some:resource`, returns 302
    6. OPTIONS request to `https://lvh.me/sign_in`
    7. GET request to `https://lvh.me/sign_in`, returns 500 because it's asking for JSON and this URL does not understand that.

That's pretty much the whole flow. The important step is number 4, the GET request to `some:resource`'s rel. You may think that the API is signing me out, but it is not. 

Here's where it turns weird: If I do this instead:

```js
import api from './api'

api.follow('some:resource').getResource()
```

I see the same process up to step 4, but this time the GET request to `https://lvh.me/api/some:resource` returns 200 and everything looks fine. If I compare both requests they are nearly identical EXCEPT for one header in the request: `Content-Length` (and one in the response, `Location`, but this is more of a consequence of the request headers I believe).

So here's the problem: Why is traverson doing a GET request when I want to actually do a POST? I'm guessing it's to fetch all and any links there may be hidden, so ok. But why is it sending `Content-Length`? I'm almost sure that is what is breaking the API. I'm unfortunately unable to dig into the API backend, so have very little visibility on the server-side.

Maybe I'm doing something wrong?

**Comment by basti1302** [comment]
The GET request at (iv) looks very much like a bug. I'll look into that.

**Comment by enrique-ramirez** [comment]
Hello @basti1302 . 

I'm sure you already suspect this, but the 302 status was my mistake. I was missing the CSRF token.
I also started using `traverson-promise` since that was more in line with what I needed.

After these tweaks, the flow seems to be good. The GET request at (iv) is no longer made (I'm a bit confused as to why it is gone, maybe `traverson-promise`?).

Here's my tweaked code so you can take a look and decide:

```js
// api.js
import traverson from 'traverson-promise'
import JsonHalAdapter from 'traverson-hal'

traverson.registerMediaType(JsonHalAdapter.mediaType, JsonHalAdapter)

const api = traverson
              .from('https://lvh.me/api')
              .jsonHal()
              .withRequestOptions({
                headers: {
                  Accept: 'application/json',
                  'Content-Type': 'application/json',
                  'X-CSRF-Token': token,
                },
                withCredentials: true,
              })

export default api
```

```js
// somefile.js
import api from './api'

api
  .newRequest()
  .follow('some:resource')
  .post(data)
  .result
  .then(console.log) // all good!
```

**Comment by basti1302** [comment]
Thanks for writing the follow up. Not sure what triggered the faulty GET request you were seeing. I can not reproduce it. Since CORS is involved, basically everything is possible. I'll close this one for now.
